receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317  # Bind to all interfaces
      http:
        endpoint: 0.0.0.0:4318


processors:
  batch: { }

extensions:
  health_check: { }

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"  # Expose metrics for Prometheus

  debug:  # Replaces the deprecated logging exporter
    verbosity: detailed  # Optional, controls debug verbosity

  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

service:
  extensions: [ health_check ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug, otlp ]  # Optional logging for debugging
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ prometheus ]
