version: "3.7"
services:
  fastapi:
    build:
      context: manually_instrumented_fastapi_service
      dockerfile: Dockerfile
      target: development
    environment:
      - ENV=development
    env_file:
      - ./configuration/manually_instrumented_fastapi_service/development.env
    ports:
      - "8000:8000"
    networks:
      - monitoring
    command:
      # TODO: use app factory
#      ["uvicorn", "manage:entry_point", "--host", "0.0.0.0", "--port", "8000", "--reload"]
      ["tail", "-f", "/dev/null"]
    volumes:
      - ./manually_instrumented_fastapi_service/:/app/


