flowchart LR

      FA[Manually Instrumented FastAPI Service]
      subgraph Observability
          OC[Otel Collector]
          P[Prometheus]
          T[Tempo]
          G[Grafana]
      end


    FA -- "metrics" --> OC
    FA -- "traces" --> OC
    OC -- "metrics" --> P
    OC -- "traces" --> T
    P <-- "metrics" --> G
    T <-- "traces" --> G